### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Samsaramunru4** [ObliqueNET/Server#1000]
Hello, I was recently banned for derogatory language on a sign in our player home, the humor I used was only intended to be seen by players within the home who had access and no offense was intended. I completely understand that the integrity of the server needs to be maintained and I am very sorry that I used such language that could compromise such. I have spent many hours on the server and hope not to lose all the progress that I have achieved. In the future, if I am unbanned I can guarantee I will not use any more offensive or derogatory language while on the server as I very much enjoy playing pixelmon with my friends and do not wish for that to be something I can no longer enjoy, thank you for reading my appeal at the very least.

**Comment by Katadreme** [comment]
I believe you are genuine in your appeal and since this is your first offence, I will unban you. But make no mistake, we do take this kind of language seriously, so any instance we find or see something similar, this ban will quickly be reinstated. Make sure you read /rules next time you are online.
