### ISSUE TITLE
Plasma Permafrost + The Pixelmon waiting glitch = waste of time

### ISSUE THREAD

**Issue by Notesboy123** [ObliqueNET/Server#1025]
I have gone through the plasma permafrost quest about 15-18 times. Half of those times I have had to /endbattle. Due to the way the quest is set up I have needed to fight all of the battles again. It takes a lot of time to go through an battle. Along with this I have lost multiple items to this glitch, and the one time I was about to finish the last battle the battle gets stuck on the waiting glitch again. I feel like it may be better for this quest to not reset all the fights, but instead it should just reset the battle you lost on/the battle you did /endbattle on.

**Comment by starwarschamp4** [comment]
The quest is setup so that you must have to fight the plasma grunts if you lose to N, this is intentional. As for the battle glitches, this is a bug in the mod and currently doesn't have a fix. If you lost items because of this glitch, you can list them in our #support channel and a mod or high ranking staff can refund them for you. Sorry you're having troubles with the battle, the boss fight is meant to be a challenge with the addition of megas, dynamaxing, etc.
