### ISSUE TITLE
I am so sorry for what i did :(

### ISSUE THREAD

**Issue by wishywoshyjoshy** [ObliqueNET/Server#1031]
I want to apologize for being a major pain and annoying all the mods I want to also apologise for pinging you all I cant explain how sorry I am I really want to make it up please believe me I was just trying to have a laugh with my friends and it got to out of hands I truly am sorry I would do anything to be able to play with my friends again I feel really bad thank you for spending time reading this i truly am sorry :( :( :(

**Comment by wishywoshyjoshy** [comment]
plz can someone read tthis i am sorry i really want a second chance
im sorry for all the harm i caused i wont do it again

**Comment by wishywoshyjoshy** [comment]
please leave a comment I'm really sorry I love your server I want to be able to play it again please :( :( :( I'm begging

**Comment by Katadreme** [comment]
Its funny how quickly you dropped the 'my brother used my account' act. Considering the fact you were temporarily banned for spamming in chat and making inappropriate comments and remarks, which then escalated to a permanent ban because you decided to ping a whole bunch of moderators of the server, I'm going to say you aren't sincere or apologetic about this appeal. So sorry no, your appeal has been declined.
