### ISSUE TITLE
I want to get unbanned 

### ISSUE THREAD

**Issue by GamerManGamin** [ObliqueNET/Server#1034]
I'm Big___Dave and before I get written off for all time I would like to appeal to get unbanned. When I got banned I was surprised, because I was just messing around and I didn't think there was much harm in it. Now I realize how much I messed up and I'm sorry. I hope you know I did more than trolling in the servers text chat, I actually enjoyed the game. I grinded a long time to get a grand total of 106-ish quest points, over 20k, 8 over 100 pokemon,  and 3 legendries including a MewTwo. I put all my free time for about a week and a half into the game, and to have it end like this is sad.  I hope for another chance to play on the best pixelmon server, and if I troll again you can ban me again. What do you have to lose by giving a second chance?

**Comment by Katadreme** [comment]
Don't think you are giving enough credit to your extremely unfunny and distasteful trolling when you say 'because I was just messing around' & 'I hope you know I did more than trolling in the servers text chat'. Especially when you did a lot more than that, like borderline harassing my staff members. And the feeble helper application you submitted and lied about getting a recommendation from the very staff members you were bothering. Only thing I agree with is your last statement. I'll give you that second chance, but just know in case it wasn't obvious, if you continue this behaviour whilst on this second chance, this ban will be reinforced.
