### ISSUE TITLE
Ban appeal NiteElSamu

### ISSUE THREAD

**Issue by NiteElSamu** [ObliqueNET/Server#1049]
Good morning, afternoon or evening (depending on when you read this).

I want to appeal the permanent ban they gave me, since I was temporarily banned for stealing some chests which were out of protection, but today the moderator PJ Lesure informed me that my temporary ban was changed to a permanent ban one day later that they gave me the temp ban.

The issue is that I had already clarified with the moderator pj lesure that I would not do it again, but that I would have to spend the ban time waiting as punishment for the 5 days of ban, in addition to returning the stolen things to the chests of the person who had them out of protection.

I know that I broke the rules and I had already been punished for this, but the extension of a punishment without warning could be considered unfair, since there was only one day left to be unbanned, in addition to not being notified.

To date, it must have been banned on Saturday, March 13, and for the edition of this I am still banned.

**Comment by Katadreme** [comment]
Let's make one thing clear. The temporary ban was advanced to a permanent ban as we had realised the way you went about stealing the chests, that being using pistons and such. So obviously, that solidify's the intent you had was nothing but malicious and not accidental, because no person accidentally steal chests with pistons. So in essence, you knew what you were doing, and you were aware of the consequences, hence the permaban. 

I understand what you mean by the extension of the punishment without warning being unfair, but as I have just mentioned, thats because we had come to the realisation of your methods. And you were already given a warning after the 1st base you stolen from, then you had gone and done it again after apologising and ensuring it wouldn't happen again. So I'm going to decline your appeal as you had your chance, and you went and did the same thing again.
