### ISSUE TITLE
ban appeal

### ISSUE THREAD

**Issue by V4MPluc1** [ObliqueNET/Server#1078]
Sorry for abusing a moderator in vc I have a short temper when it comes to people being rude or disrespecting me when I feel they are. My intentions are not to be disrespectful, being racist or being a troll. I just like joking around and my main motive is to  finish building my house, and continue on in finding darkrai. - V4MPluc1

> 
![1794ff0d02d288a1e6115d7dfbaae204](https://user-images.githubusercontent.com/82985105/115637934-59077600-a2df-11eb-839d-5b06502988a3.jpg)

**Comment by Katadreme** [comment]
I would like to apologise for the immense delay in responding to this appeal. 

To get down to business, I know a lot of time has passed since your appeal and this response, and usually I'd take into consideration that this passing of time as time for the player to essentially reflect and reconcile. However, I will not excuse any sort of abuse of my moderators. I did some investigating from my mods and some normal players about their interactions with you before and after your ban. Like you say 'My intentions are not to be disrespectful, being racist or being a troll.', they all said things that would prove you were trying to be exactly those things. Although you have apologised, I will never ever let someone enter this community that has shared pornographic material. Im not sure how someone sends a dick pic in anger to a moderator, but theres no coming back from that. Your appeal has been denied.

**Comment by V4MPluc1** [comment]
> I would like to apologise for the immense delay in responding to this appeal.
> 
> To get down to business, I know a lot of time has passed since your appeal and this response, and usually I'd take into consideration that this passing of time as time for the player to essentially reflect and reconcile. However, I will not excuse any sort of abuse of my moderators. I did some investigating from my mods and some normal players about their interactions with you before and after your ban. Like you say 'My intentions are not to be disrespectful, being racist or being a troll.', they all said things that would prove you were trying to be exactly those things. Although you have apologised, I will never ever let someone enter this community that has shared pornographic material. Im not sure how someone sends a dick pic in anger to a moderator, but theres no coming back from that. Your appeal has been denied.
 
  thats hella gay

**Comment by Rasgnarok** [comment]
> thats hella gay
It's 2021, find a new insult bro

**Comment by Katadreme** [comment]
So is sending a dick pic to another man
