### ISSUE TITLE
Was Banned for questioning Staff

### ISSUE THREAD

**Issue by beehtoken** [ObliqueNET/Server#1088]
Staff was unfair because while I was doing the Mewtwo quest I had Le_tree flying around me with fly while it wasn't active. How am I supposed to respond while I have mods doing the same quest I'm on using fly and command that are unavailable to me?
I have been nothing but fair but when a so called "mod" calls me out for calling out staff, I get banned? Is this the FTP utopia you had or is this just another PTW staff set up server you don't want me to call out? If I get banned for that, then I get banned for what I did, But your Staff has acted in an unprofessional way. What I did was nothing more than say that some staff have been abusing their /fly. While this is available to all. This is not available while no one have redeemed /fly, yet mods continue to use it and I get called out and banned for stating so. I will not apologize for what I have said. Better Yet Maybe look into mod abuse. I have been a long time player and if this is how I end Oblique than So be it. But I have been Fair in my judgement, yet reticulated by staff. This will be my last sentence on the subject.

**Comment by beehtoken** [comment]
![image](https://user-images.githubusercontent.com/67028014/116809297-1cfbbe80-aaf2-11eb-9d46-3024dc92d31e.png)

**Comment by beehtoken** [comment]
This is how some of your Smods have treated players. Go ahead and look up the time as well if fly has been active. This is mod abuse, Yet I get banned for talking about it.

**Comment by beehtoken** [comment]
Nothing but ignored unless I mention it later and get banned for disruption. How is this a fair server if this type of corruption happens without consequence?

**Comment by beehtoken** [comment]
Not testing, no anything, just doing a quest, that others where doing at the time with mod privilege's. This is not fair

**Comment by Katadreme** [comment]
You were temporarily banned for 3 days because you have continuously brought up this issue in public. And refuse to listen to reason when multiple mod staff, including myself have told you how and why the SMod in question was flying. And if I recall correctly, Le_Tree left the area soon as you started complaining. Im not sure how you can abuse /fly when its a command nearly every player can use when the booster is activated. Yes it gives Mods as well other staff roles such as Builders and Quest Designers an advantage but its completely for convenience and nothing else. And you weren't banned because we are trying to silence you, if we wanted to, this would've been a permanent ban.. We've had many players question why some staff roles have certain commands when the playerbase doesn't, but you are the only one who has taken it this far. I'm not unbanning you, take this time to cool down and stop this tirade. If you continue to bring up this issue as well as the issue you caused earlier today, then you'll be permanently banned since you continued to refuse to listen to us.
