### ISSUE TITLE
Ban Appeal - Kirikoz

### ISSUE THREAD

**Issue by Kirikoz** [ObliqueNET/Server#1091]
Hello to whom it concerns,

I'd like to write this appeal for a ban I received a few months ago. Although it hasn't even been that long, looking back, I realize how immature I must've been to have been banned from a Minecraft server and I'm making this appeal in the hopes the ban may be lifted on the basis of being a changed person. I sincerely apologize to anyone I disrespected with my comments and understand that should I be unbanned that I will be under close surveillance. I would just like a second chance to prove that I'm a changed man and matured over these last few months realizing I needed to change my attitude after being banned. I put so much time into the server and it has really sucked not being able to play with this great community and friends that I've made from playing on the server. If unbanned, I promise I won't cause any more problems and that it's all in the past. I was under a lot of stress at the time with college starting back up and other irl things happening, I ended up lashing out on the server regrettably. However, this isn't an excuse for my actions as I shouldn't have behaved that way regardless and they were in no way justifiable. I accept full responsibility for my actions and can only hope for a second chance. Either way it goes, thanks for taking the time to read my appeal.

Best regards,
Kiri

**Comment by Rasgnarok** [comment]
I will be unbanning you based on the fact you've been banned for 4 months already. I consider it a heavy enough punishment. If you understand the reasoning that led to your ban - general disrespect coupled with generous, intentional eco-breaking, then you understand that any minor issue will result in a permanent ban again.

I am content with giving you a second chance, and therefore, you have unbanned as of now.
