### ISSUE TITLE
Galarian Slowpoke

### ISSUE THREAD

**Issue by Ikkegwn** [ObliqueNET/Server#1108]
After trying to make one spawn, I decide to breed, since i got 3 galar slowbros from sweet scent. The result is 2 eggs with 2 normal slowpokes. I guess that's not normal

**Comment by juju338** [comment]
I had the same problem and had to equip both with an everstone.

**Comment by Ikkegwn** [comment]
Friend of mine said the same, trying it

**Comment by Ikkegwn** [comment]
Doesn't work either

**Comment by Vohras2** [comment]
Can you test this in singleplayer and see if it still happens?

**Comment by Forp2** [comment]
I have done so, and the bug also happened there. I have also tested galar slowpokes rather than slowbros, and it also produced the same result. I have additionally tried galar ponyta and meowth, which ponyta worked as intended but meowth did not. It seems to be a problem with mons who's evo lines have multiple forms (for slowbro f:1 is mega while for slowpoke f:1 is galar and meowth has its alolan line).

**Comment by Vohras2** [comment]
If it's happening in single player, then this is a pixelmon bug and should be reported to them. There's very little that we can do to address this ourselves. You can report it to their tracker at https://pixelmonmod.com/tracker.php
