### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by RejiUzumaki** [ObliqueNET/Server#1141]
Good Morning/ Afternoon/ Evening I was wondering if I could apply for a ban appeal. It's been a while since my ban, I was banned for raiding another claim that was unclaimed. I was wondering if I you could raise the ban since it was like in 2020. My Username used to be SIlentZepher now it's 0YukiKitsune0

**Comment by Katadreme** [comment]
Surprised you still wish to play on the server after the ruckus you caused trying to debating the server rules. And to ascertain something, you were banned for raiding that 2nd unclaimed town, literally the day after I had warned you about raiding and stealing from unclaimed towns. However, a great amount of time has passed since then and I hope you have a altered demeanour about how you conduct on the server. I will be unbanning you as a final chance, any further rule-breaking with result in a permanent ban that won't take into account any future appeals.

**Comment by RejiUzumaki** [comment]
I understand and have learned from my mistakes and will watch what i do from now on.
