### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by NicClassic** [ObliqueNET/Server#1151]
I'm looking to get unbanned idk why i was banned it says i was banned by the autobanner. My Ign is NicClassic and i just want to play again.

**Comment by Katadreme** [comment]
Yep, you were autobanned and heres why: 
![Screen Shot 2021-06-22 at 5 33 05 pm](https://user-images.githubusercontent.com/50907133/122882945-0a7a6480-d380-11eb-94da-a86effe16b92.png)

Although almost a year has past since your ban, don't think that that kind of unwarranted response to any statement is acceptable so your appeal has been declined.
