### ISSUE TITLE
FilthyYasuoMain's Ban appeal.

### ISSUE THREAD

**Issue by QueenYasuo** [ObliqueNET/Server#1156]
I've been on oblique for awhile, I have tons of friends there. 

So I couldn't sleep at around 5am, cancer bullshit. 
I was in a pretty bad mental state to begin with so getting on wasn't my best idea. 
I was joking around with some people, obviously the staff member at the time didn't appreciate my jokes. Even though leads themselves make the deeznuts jokes consistently. Then I said the word fuck to zoru, I was talking about her saying fuck work. 
Then since he gave me a second warning for something so trivial he made me unbelievably mad and without thinking, or caring even though I knew it was wrong. I placed signs talking a bunch of shit and was going to have him tpa for a look. Anyways, I'm sorry for the signs but not the things I was warned for as it was extremely trivial.  He didn't even see my signs until after he banned me for 5 days, for cussing once. If I get unbanned, which I'm hopeful for but won't hold my breath. I'll try to do better and not let my anger and bad mental take over before I go off the rails. Thanks for reading and uh, sawk.

**Comment by QueenYasuo** [comment]
I am genuinely  sorry

**Comment by Katadreme** [comment]
I have been dwelling on what decision to make about this appeal since your ban. There was obviously a miscommunication or misinterpretation of comments / humour here in which caused this whole incident. You are correct, deeznuts jokes and swearing (in moderation and not used in aggression or hurled at someone) is a common expression nearly all players use. I understand the staff member at the time was being little too strict in the preservation of rules and they have been informed and have ensured in being not so. The signs however are very hard to go unnoticed. I have heard from others you do regret the words that were written as they were a product of your mental state. But they were some bad words indeed. Hard to understand why you could say such things when most of the players you interact with on the server are staff members. 

I digress, ultimately, I have decided to unban you. I ask you to not immediately let your mental state take over your actions. Harder said than done obviously, but needed to be said.
