### ISSUE TITLE
LimitlessJoker Ban Appeal: Got Perma Banned for Testing an Exploit as Staff, I would like to be Unbanned.

### ISSUE THREAD

**Issue by LimitlessJoker** [ObliqueNET/Server#1165]
Originally written on 08/07/2021 7:00am BST
Basically I was testing the exploit and apparently that’s it’s classed as “ABUSING” 
I only found it yesterday morning and was going to report it tomorrow I would have done it today but it’s 7am and i wanted to sleep, I only did it Like a couple of times just to test it. That is it. 

The Exploit:
I tested to see how the boundaries work to trigger it, as there’s like an invisible block above the loot and by hitting the invisible block it reset the loot below it, Essentially it was an infinite loot glitch that allowed the loot to be constantly replicated from hitting the invisible block after claiming the Beast Ball Loot. However, after after telling another staff member (who will not be named) they proceeded to report me to assume I was using this exploit to my advantage which you will find i had no need to do so as i run a very popular shop from making purchases from people and having people help out in the shop (Which i would pay them for accordingly, your welcome to use  Carrot Report for that as I give money to my assistant Mr WitherDiamond21) I was not going to keep any of this loot and I always had disposed of it afterwards except this occasion because i got banned before i got the chance. I feel like this is a mistake as I love being a tester/games tester and I've been working really hard to be deputy and higher ranks for the Staff Community. I would love to be unbanned for being wrongly accused of abusing the server that i love to play every single day and hopefully kindly ask for my staff Privileges back.

I hope this message finds you well.

From Joker.

**Comment by Katadreme** [comment]
I guess classifying as what you did as 'abuse' may be inaccurate, however that doesn't make your situation any better. I can confirm nor deny you sold any of the loots you had obtained but you did keep some in chests from what we uncovered. I'm having trouble with this appeal because, well frankly I'll say it how it is, sounds very entitled. Also your actions and your words dug your own grave. You were banned because, when put simply, you found a very easily abuse-able and unknown exploit involving Beast loot. You try to defend yourself by saying your a tester of games, which is fine, but you aren't one here. You have barely any sort of perms to properly test the exploit, in which then admins should've been contacted since they have nearly all the tools compared to a Helper. 

This easily could've been avoided had you of just told an admin or told another person to tell an admin. When I confronted you about the loot you said you planned on informing me in the morning. But your words to the person you told the exploit about prior proves this to be untruthful. Here's you first telling them about it: 
![Screen Shot 2021-07-12 at 12 50 47 am](https://user-images.githubusercontent.com/50907133/125199897-b17d5c80-e2ab-11eb-824e-d7e8fffbcdf4.png)

And to seal the deal. Here's how you reacted after they told you they had to tell someone:
![Screen Shot 2021-07-12 at 12 37 10 am](https://user-images.githubusercontent.com/50907133/125199912-c2c66900-e2ab-11eb-96cb-6dff399700a9.png)

From the looks of it, it seems like you just adopted this 'I was planning to tell you later' story because that seemed as the most plausible and believable story, since the exploit was going to be told to the admins. However there so many other cracks in your story that it was too hard to not doubt. You may have been wrongly accused for exploit abuse but you have been rightfully accused of lying. You are neither being unbanned nor getting staff privileges back.

**Comment by LimitlessJoker** [comment]
I told him not to tell as i didnt want it to be leaked for public use but i guess whatever

**Comment by Katadreme** [comment]
Fam you literally asked the guy to 'turn a blind eye'

**Comment by LimitlessJoker** [comment]
And once again everyone is taking that out of context.

**Comment by Katadreme** [comment]
This'll be the last time I say anything since this has been closed but, what other context could this be seen in? 'Aw nah please dont' and 'turn a blind eye just this once'. If you were trying to keep the other player from telling anyone why not say 'Dont tell anyone otherwise people could abuse it'? Why speak in code?

**Comment by LimitlessJoker** [comment]
Because i didnt want the information leaking out to anyone as it was my little case test to prove i could easily find exploits within the game and of how to prevent them. That is what my future job is going to be as a Games Tester. The bottom line is if you had given me the opportunity the report would have been filed for tomorrow about what i had discovered.
