### ISSUE TITLE
Ban Appeal: PrinceLokiii

### ISSUE THREAD

**Issue by PrinceLokiii** [ObliqueNET/Server#1170]
I was banned from Oblique sometime in mid-March of this year. Since then, I have foolishly tried to cheat the system and bypass the ban which I did deserve. I know exactly why I was banned, I took a good while to think about it. I was an arrogant, self righteous shit head and there is no excuse I could give for it. To all the staffers and players I have wronged, I am very extremely sorry. To the one I feel I have wronged the most, you received my heartfelt message already. I am sorry for my self entitled persona I displayed, I just got so caught up in it and myself I became very foolhardy. Instead of facing that reality and working to better myself, I first tried to turn away from it and look the other way, as a coward would. To the ones I have lied too, I am sorry for trying to deceive you, the Management team cares significantly about the staff team, and the player base as whole. There is no excuse for my actions like I said. To those that will hear me out, and given the chance, I really would like to give a personal apology to the ones I have significantly wronged Oblique is a fantastic server, fun-filled server, and I know I can't really be forgiven for trying to taint the image, The players and staffers make the whole server one of the best, and I am sorry to you all for my behaviors. I know there is no way to prove that I am truly remorseful, or that I have really worked on myself the past couple of months, but all I can ask for is forgiveness. Thank you to anyone who reads this, and to anyone that responds, have a wonderful day!

**Comment by AdmiralCrunch56** [comment]
Since you're an old member of the Oblique community I'll spout some old names that have committed very similar actions to what you did and we can see how the Oblique community has handled them. XCasualty and BammaBoy both used alt accounts in discord and on the server to harass our staff after their ban. While you weren't throwing racial slurs or flooding the chat in spam like they did, the action of using alternate accounts to avoid a ban is extremely punishable and something we never take lightly. 

We haven't even scratched the surface on your actions that got you banned initially which say numbers on how this ban appeal will go. Your initial ban reasoning was due to you lashing out against Diddys promotion and the little messaging you did to other staff members saying how we admins don't care about our staff. Let's start with this quote you sent to me in dms. 

> Completely Diddy getting Admin. I mean come on, I know you didn't pay much attention but for months I worked my ass off to get that spot to further benefit the wizard team and Oblique as a whole. Diddy on the other hand, is the newest wizard to the team, does nothing to contribute, doesn't currently have an active event, and quite frankly, doesn't show capabilities to be an effective leader. Now of course it's all my opinion Admiral

What we look for when deciding who's the next admin isn't about how much work they do when we need an admin but the work they do beforehand and how they act. Diddy was an active staff member who never went out of his way to chase positions, which makes him sound like he'd be responsible for leading a position. While you on the other hand explicitly state that you worked your ass off for the position. This isn't some manager job at your fast food chain where all they look for is someone who they can work to the bone. We want people who do their stuff because it's fun, not for some stupid discord tag. Power hungry fools are the last thing we want to have being in charge of other people which is exactly why we picked Diddy for the job. Dough is another excellent example as he was essentially doing the job of gym lead before getting the tag because he just wanted to make the community better. 

This isn't some Hollywood crap where you can just vanish for a little and return thinking we'll forgive your actions. You were an ass to the community so we'll treat you like one. This appeal has been **denied** with no chance of changing.
