### ISSUE TITLE
Nuking_Lizards Ban Appeal

### ISSUE THREAD

**Issue by NukingLizards** [ObliqueNET/Server#1173]
### **Information:
IGN: Nuking_Lizards
Discord: Nuking_Lizards#4702**

Dear Oblique,

I would like to first state that I'm humbly sorry for my actions. My actions will never be forgotten but I hope for a day where we can look past my idiotic mistake. I was banned a couple of months back for abusing my perms. Said perms was access to Creative to spawn in copious shrines that I sold to Admin shop to generate copious amounts of money. I was reasonably banned, permanently, which is extremely justified. A week later I used a VPN and a relatives Minecraft account just to see what has happened to my town (Now revamped to TkTownies) I was banned again for use of an alt.

I would like to be unbanned because I miss the community. I miss the friends I've made and friends I haven't yet made. Although I have a 0% chance of ever becoming staff again, I also miss helping the player base and the community. My actions can not be justified by any means. However, I would like to grow past my mistake and be welcomed back into the amazing pixelmon community. I am a dedicated player and a very generous player as some may know. I hope for the day that we may meet again. 

Kind Regards,

**Nuking_Lizards**

> It’s not an easy journey, to get to a place where you forgive people. But it is such a powerful place, because it frees you.
> 
> — Tyler Perry

> Forgiveness says you are given another chance to make a new beginning.
> 
> — Desmond Tutu

P.S. Kata, I hope you are happy with the grammar, punctuation, and spelling. I'm still trying to make you proud. <3

**Comment by Katadreme** [comment]
I won't be unbanning you because this appeal is way too early. You were banned on the 3rd of June. August just started. Especially for how large the extent of permission abuse was, this is too early. I understand you may be genuine with your apology but you knew what you were doing. The spawning in and selling, clearly methodical. If you miss the community and friends, should've never risked it in doing something so foolish. Not even going to bother with the alt because that dug your grave even deeper. 

Also next time you do an appeal, don't add quotes, especially ones telling the person deciding your outcome how to think or feel. We're well aware what forgiveness is. We just have to determine if you're worth enough to get it.
