### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by Dunceboy** [ObliqueNET/Server#1177]
Hello My name is Dunceboy99. I said Cum shit piss in chat three times and got perma banned. I will not do it again and am very sorry for the inconvenience. I was having a very fun time on the server with friends and made new friends in my town. Looking forward to playing. :)                 

                                                                                                             - Dunceboy99

**Comment by Katadreme** [comment]
You actually did it 4 times and I'm very confused as to why you spammed this exactly? Because if you were really having a fun time on the server, why do something that would get you banned? Especially after being warned several times to stop? If you were banking on me unbanning you think again. Appeal's been denied.
