### ISSUE TITLE
ban appeal

### ISSUE THREAD

**Issue by pog02309** [ObliqueNET/Server#1185]
it says my ban for 5 days on the account 'doopio' was made permanent for ban evading, but I never ban evaded. my friend using the account '_Tem4ik' pretended to be me, but I never did anything myself. this is made evident by the fact that we both have different unique inventories and pokemon and were on the server at the same time doing different quests. you may also recall the time when we both went to the trivia night and answered different questions, which would have been impossible if '_Tem4ik', my friend, was an alt of 'doopio', myself. I'd like to request that we be unbanned from the server as we have both been banned for over a week and are first time offenders.

**Comment by Katadreme** [comment]
Just because you are first time offenders, doesn't mean you can get off scot-free. Your actions, as well as your "friend's" leading up to the ban was pretty awful. You had spammed these two big gross paragraph of text at least 5+ times: 
![Screen Shot 2021-09-05 at 2 41 26 pm](https://user-images.githubusercontent.com/50907133/132115551-ffa40a5c-78f3-41dd-92b3-ecc8cfd8a360.png)
![Screen Shot 2021-09-05 at 2 41 02 pm](https://user-images.githubusercontent.com/50907133/132115553-1637dd23-287b-4d6b-b4a5-0648a224bdb9.png)
Then you said this to which you were promptly banned: 
![Screen Shot 2021-09-05 at 2 39 36 pm](https://user-images.githubusercontent.com/50907133/132115556-28f86313-9cd4-4498-ace9-9b462bb2ca69.png)

Then no less than 4 minutes later your 'friend' logged on and immediately said: 
![Screen Shot 2021-09-05 at 2 47 35 pm](https://user-images.githubusercontent.com/50907133/132115610-94e3b3cb-2da9-46b8-94e4-240a4f05439f.png) - and spammed that last msg in the screenshot few more times. 

Don't know why your 'friend' wanted to immediately pretend they were you and continue on the onslaught of spam, but if your actions said anything is that this server would be better off without you and your friend in it. Appeal has been declined.
