### ISSUE TITLE
How do i unban my 7 year old?

### ISSUE THREAD

**Issue by LFSH11** [ObliqueNET/Server#1188]
My 7 year old has got himself banned from oblique server for what he thought was just a battle.
How can I get him unbanned as he had no idea he was in the wrong as he can't read or write obviously after explaining to him why he was banned he now understand he can't "battle".

**Comment by Katadreme** [comment]
Almost had me fooled with the act here, but I do thorough checks on all banned personnel and look what we have here:
![Screen Shot 2021-09-23 at 5 05 04 pm](https://user-images.githubusercontent.com/50907133/134467404-7d4341fd-7fdf-4b5e-a660-e0bf847a7d42.png)
Your 7 year old seems to have exceptional english skills. Even if this did happen to be a 7 year old, and someone else had taken over when they wrote that sentence, doesn't hide the fact they knew full well what they were doing, since literally this LSFH11 player had joined the server, all they did was PVP people at spawn. Appeal has been declined. Hopefully you can explain that to the 7 year old.
