### ISSUE TITLE
Ban Appeal: JackDimonds

### ISSUE THREAD

**Issue by JackDimonds** [ObliqueNET/Server#1194]
I feel that it has been a reasonable period of time from my ban to rejoin the community. If you have forgotten me than that is also reason enough to rejoin the server and be unbanned. 

USER @ THE TIME: JackDimonds
CURRENT USER: JokerMoment

**Comment by Katadreme** [comment]
Well this would be a very unlucky day for you because I just so happen to be who advised the moderator who banned you, to ban you. I remember you very clearly because since your departure, not many folk have come to the server that have matched the level of toxicity and disregard for rules and authority. And the cockiness you used to have is still prevalent in your appeal here where you 'if you have forgotten me then that is also reason enough'. Regardless of how long the ban has been for nor the reason for the ban, saying 'its been so long, you probably don't remember so I should come back' isn't really good enough reason. Appeal has been denied.
