### ISSUE TITLE
True Apology and The Last Ban Appeal.

### ISSUE THREAD

**Issue by LimitlessJoker** [ObliqueNET/Server#1207]
*The True Apology Of The Joker who played himself a fool*

Dear Oblique Staff and the Community,

I have been sat for hours trying to come up with the true apology letter and one last attempt of what’s left from the bottom of my heart of a ban appeal.

I would like to first state that I'm very much sorry for my actions and a sorry to those who may have been affected. My actions will never be forgotten but I hope for a day where we can look past my idiotic mistakes in life. I was banned a couple of months back for abusing my perms and for my abusive mental health issues and for that I’m truly sorry from the bottom of my heart and would like to atone for my deceptive ways I realise I’ve not only let the community down but the staff and Ras down and I uphold myself with my true apology to show I’m sorry. I’ve taken therapy which is going extremely well and had told me to try and give this server another attempt in trying to have it welcomed in my life not only for my own benefit but for the benefit of a community I love from the bottom of my heart since first playing on the server. 

I would like to be unbanned because I miss the community. I miss the friends I've made and friends I haven't yet made. I also miss helping the player base and the community. My actions can not be justified by any means and can only be seen as a way of development and moving forward. However, I would like to grow past my mistake and be welcomed back into this pixelmon community. I hope for the day that we may meet again.

Kind Regards and Best Wishes to the Server’s Success,

LimitlessJoker

**Comment by CenizaRey** [comment]
I’ve spent a long time thinking about this. The fact you would approach Ras several months after the event looks favourably on you because it proves you care about rejoining this particular server. 

We get a lot of people who make several ban appeals, but they usually happen in quick succession and they usually give up after a few hours. 9 months, however, is a long time to wait, and I believe enough time has passed to warrant you deserving a second chance. 

However, what you did was a major breach of trust. Your first instinct should have been to tell a superior member of staff, not to ask other staff members to turn a blind eye after you couldn’t help but show off your discovery in an attempt to feel intelligent because you had  ‘beaten the system’.

Perhaps your intentions were to tell an admin, perhaps not. Only you know that for sure, and potentially having someone who would exploit our weaknesses and oversights on the staff team is not a chance we are willing to take.

As such, you will be unbanned effective immediately, but you will not have the opportunity to join any branch of staff again. Furthermore, you will be on a final warning for the first 3 months from your unbanning (today).

That aside, welcome back to Oblique!
