### ISSUE TITLE
Ban Appeal: DAlmightyPizzza

### ISSUE THREAD

**Issue by DAlmightyPizzza** [ObliqueNET/Server#1213]
On July 4th of 2021, I may have had a Few choice words/said a slur, and I got banned. Whilst I have no excuse aside from being intoxicated (which is not an excuse) I do feel that I have grown as a person and I would like to apologize profusely for my actions. While I have a few friends on the server I do not want that to affect your choice in this appeal. I know what I did is wrong and while it's a given it will not happen again.
p.s. I miss trivia UwU

**Comment by Katadreme** [comment]
Things you said at that time were quite vulgar and hard to dismiss. I recognise the fact you have apologised and do sound sincere but still feeling little unconvinced. However, it has been 6 months and your conduct on the discord whilst being banned from the server has been for the most part quite normal. Because of that I'll show leniency here and accept the appeal. But like you say, it will not. Happen again. Understood?
