### ISSUE TITLE
bAN appeal 

### ISSUE THREAD

**Issue by FirstNameTaylor** [ObliqueNET/Server#1214]
the night i was banned was over exaggerated because the staff that told me to change the subject got me banned without even giving me a warning and i think thats unfair, we were all talking about the same subject and i may took it too far without realizing. so if i can talk to someone to explain this more thoroughly that will be cool

**Comment by Katadreme** [comment]
Firstly, you were warned this time around before you were banned. However should be of note, although this instance wasn't as severe as your previous instances, you were banned here because you had 3 chances and this was the 3rd. There are only so many chances we can give, and if you haven't learned when to control the things you say by now, there isn't much else we can do here. Appeal has been denied.
