### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by CannaCasual** [ObliqueNET/Server#1219]
Hello, I was banned previously for being a bit toxic to the staff, It has been quite a while, maybe a couple years even since it occurred. 
I would love the chance to play on your server again, I do regret and apologize for the things I said.

**Comment by Katadreme** [comment]
Has been approximately year and half since your ban. 'Bit toxic to staff' is putting it very lightly, considering the various things you said to staff, including the server owner herself. Does beg the question why you'd want to return to the server, after the high disdain you held the server at. Regardless will be declining this appeal as it is very plain and doesn't recognise the severity of your actions and your ban.

**Comment by CannaCasual** [comment]
Ok. No excuse for my actions, all I could do is prove it via action. Truly am apologetic, the lack of emotion that is portrayed via text makes that hard to tell. I honestly don't remember the majority of the argument or things I said, just remember getting in to it with one person specifically. I didn't really expect to be unbanned but enjoyed the server enough to donate previously so I thought bygones could be bygones and start a new. Cheers to you all and a happy new year.

**Comment by Katadreme** [comment]
You showed all the few brain cells you have by thinking I'm a woman or whatever you think I am. It's a shame to have to ban you from this Github because I'd love to see you make an idiot out of yourself even more than you already have.

**Comment by Rasgnarok** [comment]
I genuinely hope you seek help, @CannaCasual. That was honestly shameful, embarrassing, and completely deranged.
