### ISSUE TITLE
Ban appeal 

### ISSUE THREAD

**Issue by FirstNameTaylor** [ObliqueNET/Server#1227]
I would like to apologize on past topics i talked about first of all and I have reflected on what I have said and wanted to play the server again but without any profane language or sensitive topics. Just play the game to have a good time again with the boys. 

- Taylor

**Comment by Katadreme** [comment]
Well Taylor, its been about 2 or 3 months since your first appeal. I apologise for the delay in responding. I'll level with you. From the various conversations we've had I you are and can be a better person than you were in the past. I understand several factors couldve played into the reason as to why your behaviour was eratic but I trust that now you've matured enough to stop yourself before doing anything hasty. So I will unban you, but you will be on a short short short leash. I will not be having any sort of rule breaking or rude / offensive / racy remarks toward other players or staff. Hope I've made that clear.
