### ISSUE TITLE
OrangeSodaPop discord and server unban

### ISSUE THREAD

**Issue by OrangeSodaPop** [ObliqueNET/Server#1252]
Hello, 

If possible, I wish to be unbanned from the discord server and Minecraft server.

I was banned for trolling and disrespecting staff members on the Minecraft server a few months ago, I was for the most part unaware that things I said were disrespectful to staff members, and for that I am sorry. And for the trolling, I do admit that it was something I did but was also unaware it was harmful, nor did I intend for it to be harmful. although I do know some of my acts of trolling were a bit more mean, such as using a trap on people, however, I did warn them of the trap on most occasions. However, I only did this to staff/players I knew and didn't think it was particularly harmful to them. And, for the discord ban, which over a year ago was caused by some of the memes I sent being mobile crashing gifs, while I did it intentionally the first time, the second time I did it was accidentally, as I thought it wasn't a crashing file, and for that I am sorry.

Anyways, I will avoid doing these acts from here on.

Sorry,

-OrangeSoda

my disc is OrangeSoda#1769 if you wish to contact me about anything else or to clear up any issues.

Have strawberry elephant
![C128A4FB-F884-4E41-B08C-96F10E034B19](https://user-images.githubusercontent.com/57567713/170164260-1e7975e7-186e-4084-bdf0-320408beb45e.jpg)

**Comment by fatyg5** [comment]
Gonna start this off with the fact that I'm rarely involved with bans unless needed so I decided to look into your past activity and bans before responding.

I've found your original Discord ban regarding a crashing gif that you posted as a "joke". I also see mentions of death traps you purposely teleported players to, to kill them. 

I also see mentions of other trolling you continuously acted out within the server and Discord , with warnings, among other things, as your punishment.

It seems obvious from these facts, especially the repetitive trolling you continued to do, even after your multiple warnings, that you failed to learn nothing over the course of the 1-2 year span between your playtime-ban-playtime-ban period. I'm unsure how you expect me to believe that this current 6 month hiatus has taught you anything.

You seem to understand that a death trap is bad, because you say you warned users about it before they teleported, but I find it hard to believe that people would willingly teleport to you and then make reports of you killing them in such traps unless they had no clue what they were teleporting to.

I also believe that in a ban appeal you show sincerity,  and your appeal just feels like you just acknowledge you did things, but don't see why they were bad. Furthermore, you posted a picture on your ban appeal that is of zero importance to the appeal and makes me feel even less so of entertaining your appeal. 

I recommend you think about my response and the quality of your ban appeal. If you sat down, wrote this appeal, and said to yourself "Yeah this is the one to get me unbanned", you're mistaken. 

For the above reasons, your appeal is denied.
