### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Smeuner** [ObliqueNET/Server#479]
Just a couple of minutes ago I was banned from the server for swearing. Me and my friend were messing around with signs in our base/house. I changed a sign and he asked me something stupid so I responded with something stupid. I honestly thought I was still in our town chat because I wouldn't just say something like what I said in the global chat. I'm honestly sorry for not paying more attention to what chat I was talking in, and if you do decide to unban me I will make sure that never happens again. I also got banned for ban evading because I went on the server with my alt right after I was banned, I was asking about speaking to a mod and what I should do now my main account got banned. But before I got an answer I was banned instantly. I'm sorry for both things and hope you believe me and trust this will never ever happen again.

**Comment by Smeuner** [comment]
sorry, I forgot to add my IGN. It's Smeuner

**Comment by Rasgnarok** [comment]
You were ban evading, that's why your second account was banned. You could have easily simply checked the discord for information on how to appeal. 

As for the original ban, you were caught by the autobanner for saying the word 'faggot', which is why it was an instant ban. This is a failsafe to prevent users to spam on first join. I will unban your main account in the coming 5 minutes. Please remember that some words, like that one, are filtered.
