### ISSUE TITLE
Suggestion: Personal Claims

### ISSUE THREAD

**Issue by lolsikinz** [ObliqueNET/Server#485]
What if we have a claim system separate from the town claims so each player can claim like 10 chunks outside of their town (or more to be buyable) with all the inplied privacy of your own claims and still have the town claims left for the town.

Some people are paranoid of joining towns because of people stealing (I'm one of them) and it would help said people that want to be in towns but are afraid that someone will steal their sweetrolls.

**Comment by JellyBlade** [comment]
I like this idea, but I fear it could be easily abused.
I'm also not sure how useful it would be for _some_ people like myself, an independent mayor who doesn't feel like joining another town, but that's just me.

But it would definitely help with people who want to build separate from a town, and still be in that town without using up valuable outposts.

**Comment by fatyg5** [comment]
Personally I'm not a fan of this, it defeats the point of towns. If you don't want to join towns because you're afraid, make your own, you can establish a town alone and buy plots from towns instead.

**Comment by lolsikinz** [comment]
I now see the issue with this and would like to add a different version of it. Make it so the 8 claims every person grants a town is theirs and theirs alone in the town kind of like plots but players themselves pick the chunks they want/need either by picking chunks claimed by the town or claiming additional chunks for the town.

**Comment by RudolfShmitler** [comment]
Your suggested version is that every player gets their own 'chunks' instead of plots, is that right? In that case, I don't see an issue as to why you can't just create a plot. Members of your towns (Not Executives) cannot access something not within the general town area and plots that are not owned by them. I have seen/heard about mayors being able to disallow members from editing or accessing blocks within the general town claim as well, which leaves them only able to access their own plot. If there is a trust issue between sharing items/chests, simply promote no one and have all your chests in your plot. This is just my recommendation based on your follow-up comment. If you think there's anything wrong with it, comment away.

**Comment by Vohras2** [comment]
Closing this since it's super old, and I think valid counter-arguments have been made.
