### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by duckmangamer124** [ObliqueNET/Server#495]
Hey there person who this is going to,it is I, Duckmangamer124, listen I am very sorry for saying what i said to the man who was insulting Ras and the server. I had no idea what I was doing while I was saying what I said. I am not really like this, I am only like that when i am either sticking up for someone or something or just plain out mad and pissed off. I have never said that ever in my life nor will I ever do that again.It is fine if you don't unban me,but i will miss playing Oblique and having Pixelmon at my PC. If I dont get unbanned,just know it was fun playing Oblique and I will miss playing Pixelmon and battling bosses. And supermatt57 gets all my things.

in-game name=duckmangamer124

Sincerely, Duckmangamer124

**Comment by duckmangamer124** [comment]
I am very sorry about what I did and will never say anything bad ever again on servers

**Comment by duckmangamer124** [comment]
I have never done an appeal in my life,so I am very sorry if this is not good,and i hate myself for what I have done to that person. My apology to you moderators and admins
Duckmangamer124

**Comment by duckmangamer124** [comment]
My discord user name is @Hawk Birb#3664 if you want to talk there

**Comment by Rasgnarok** [comment]
This is the second chat-related offence you have been called out on. Because usually chat offences do not get a permanent ban, I'll unban you this time, as a second chance. Your unban is effective immediately, and remember - the mature reaction is to control your anger and your words. Anything else makes you just as much the bad guy.
