### ISSUE TITLE
Discord Ban Apeal

### ISSUE THREAD

**Issue by HellasMorona** [ObliqueNET/Server#503]
I don't really remember what I did to get banned, I was told it was from staff disrespect. Been a bit since I played on the server. Im sorry for being rude. I dont really know what to say lol. I need the discord to get more involved in the server and to use the market. So it would be helpful. Thanks-Hellas

**Comment by Rasgnarok** [comment]
I need your username so I can look into your ban. Can't find anyone under Hellas, or HellasMorona.

**Comment by Stega01** [comment]
I was just notified I was removed from the discord because "You are being removed from the Oblique Discord because I'm pretty sure you're one of the raid bots. If this is in error, say so" Im not one of these "raid bots" idk what they even are ive just been playing focusing on legendary quests the past few days currently working on the articuno quest

**Comment by valuta1995** [comment]
Make your own issue (a.k.a. post/appeal), don't hitch onto someone elses.

**Comment by fatyg5** [comment]
No reply for 23 days. Closing
