### ISSUE TITLE
ban appeal 

### ISSUE THREAD

**Issue by jabahut78** [ObliqueNET/Server#511]
I made a mistake I did not mean to say that in chat my game crashed and I made a mistake I promise I will never make that mistake again

**Comment by Rasgnarok** [comment]
You were caught by the auto-banner for saying a racial slur. That's not "my game crashed and I was mad", that's "I can't control my anger". I am unbanning you because the autobanner is meant to catch trolls, and I don't believe you are one. But if it happens again, this will be permanent. You've now been unbanned.
