### ISSUE TITLE
Ban appeal (alting??)

### ISSUE THREAD

**Issue by Arenstoner** [ObliqueNET/Server#512]
Hey, so I just tried to get on oblique and I saw that I am banned for using an alt? 
I'm aware around rules of abusing alts (I think) and I'm sure I didn't abuse in any way. If I did I apologize for doing so. If even using an alt for any reason whatsoever is not allowed then I'm fine with keeping my alt banned but I'm here to ask if you could unban my main (IGN = Arenstoner). I never saw any rules however on not being allowed to get on an alt at all so I'm sorry if I did break that rule. 
I hope this issue can get resolved soon as I just purchased a rank and was really enjoying myself on oblique

**Comment by Arenstoner** [comment]
I was just made aware of rule number 10. I apperantly can't use /invitefriend on 'alts' either. I did this on my first day on the server on one of my brothers accounts (that I also have acces to.) Now, I talked to him and he's fine with staying banned as he doesn't play that much anyway. So perhaps that's an option to resolve this issue.

**Comment by Arenstoner** [comment]
Discord is Aren#0002 if you want to talk there, considering its much easier.

**Comment by Rasgnarok** [comment]
How many accounts do you have registered under Oblique?

**Comment by Arenstoner** [comment]
I honestly don't know because I also have a sister (Tashanie) who plays minecraft regularly and has multiple accounts, but I can tell you my alts are Smeuner(the brothers account) Smeuners and Jammers.

**Comment by Rasgnarok** [comment]
According to logs, it was found that voting money as well as pokemon was being transferred from some of the secondary accounts to your top account, and vice versa. InviteFriend was not the only feature that was therefore abused by the alts registered to your account, that are more than just the four you've declared. I find it more than bizarre your sister is a new character in the claim, as she did not request an unban. If she did indeed play regularly, she would've said something for being banned for your actions.

**Comment by Arenstoner** [comment]
I wanted to say my sister plays *minecraft* regularly not the server. I mentioned her because I thought I was only caught for using the friends invite command on that account. But alright. I apologize for my actions. It shouldn't have happened and I'm truly sorry. I hope you give me one last chance. Hope to hear from you soon

**Comment by Rasgnarok** [comment]
This is what led to your ban:
NaomiWirth90 asks Frost_Wolf for a Charizard, which he receives immediately. Upon receiving, NaomiWirth90 sends it directly to Mad_Gamer, and logs off. Now that already means there's a missing Pokémon from Frost_Wolf, who then escalates the issue to staff for stolen goods. Mad_Gamer, without ever having messaged Smeuner, sends it directly to that account and also transfers 17000 to Smeuner, who then also logs off.
Finally, the Smeuner account transfers everything to Arenstoner, totaling 27425 eco atop. The funny thing is, Smeuner is aware of the Frost_Wolf theft, because that account spoke to him about whether or not the "issue with your charizard" was sorted.

Here's a choice compilation of logs.
![image](https://user-images.githubusercontent.com/18584380/80893379-d46fb200-8c9f-11ea-8ad0-84cefe88bafb.png)
![image](https://user-images.githubusercontent.com/18584380/80893382-d9346600-8c9f-11ea-9666-eb3f2cc5fec7.png)
![image](https://user-images.githubusercontent.com/18584380/80893388-dc2f5680-8c9f-11ea-95f4-4cfd68739659.png)
![image](https://user-images.githubusercontent.com/18584380/80893391-e2253780-8c9f-11ea-8b3e-d1b34f4c9606.png)
![image](https://user-images.githubusercontent.com/18584380/80893395-e5b8be80-8c9f-11ea-962b-b4aff6b30892.png)
![image](https://user-images.githubusercontent.com/18584380/80893399-e94c4580-8c9f-11ea-976a-243cacd6a1eb.png)


I'd love you to explain why these accounts all acted as a siphon for a stolen Charizard, and pokedollars atop of it.

**Comment by fatyg5** [comment]
Due to two weeks of inactivity, I'll chalk this to having no reply. Closing.
