### ISSUE TITLE
Server ban appeal

### ISSUE THREAD

**Issue by PlasmaisBtch** [ObliqueNET/Server#525]
i was banned for talking with my friends and saying some bad words too much, didnt think saying shit and you bitch to my friends was too much but i was banned for it, can i appeal to play with my friends again

**Comment by PlasmaisBtch** [comment]
can i play???

**Comment by ElementalMP** [comment]
Hmm, this appeal was buried under many quest issues. I am sorry it took so long to get to. You say here you were banned for saying too many bad words to your friends, but this is far from the truth.
Your official ban reason is: "Consistently pushing staff and the rules, ignoring all warnings."
You were banned due to being racist in chat as well as being generally offensive, replying to all warnings with "Ok daddy" then proceeding to completely ignore whatever warning you had just been given. An example of this is you being told to leave the trivia area, and teleporting back in within a minute or two of being removed forcibly. 
For these reasons, you will not be unbanned.
