### ISSUE TITLE
Pokeload and /vouchers during server reset

### ISSUE THREAD

**Issue by Chewyspedoodle** [ObliqueNET/Server#536]
Hey! My IGN is Chewyspedoodle, and I've been around for quite some time on the Oblique server. When I logged in today for the first time since before the reset, my /pokeload said that there was an error or I did not store a poke before the reset. I distinctly remember storing my 5IV, shiny Ash-Greninja. He's my darling. Also, I had some store-bought vouchers I got with my Enigma rank a long time ago that I was under the impression would transfer over. I have attached a screenshot of some physical vouchers that I would like transferred as well, if possible. In game, I currently have zero vouchers of any kind, at the time of making this post. Any help that can be offered to me would be greatly appreciated. Thanks! :D 
![Screenshot (512)](https://user-images.githubusercontent.com/66456494/83837487-8c8be280-a6c4-11ea-8741-eed72f0e8c4c.png)

**Comment by Hiroku** [comment]
Seems there is a bug in the Cross Server Bank. I've accessed the storage files directly and your Ash Greninja is in there safe and sound, but for some reason the website program isn't loading it and so neither is the plugin. I'm looking into it, if it's not working in the next few days, post here again and we'll manually return it to you. 

If a moderator sees this and the time to return it is now, message me and I'll send you his Pokemon's data file.

**Comment by Chewyspedoodle** [comment]
Thanks for answering, Hiro! Does what you just said apply to /vouchers ? Also, are the vouchers in the screenshot transferable?

**Comment by Hiroku** [comment]
I don't remember our latest policy on the vouchers; I attempted to write a transfer for the vouchers but it never ended up working. I was flipping my shit because of how frustrating it was, shouldn't have been so difficult. But yeah I'm not sure whether moderators are good to reimburse those, I'd let them make that decision.

The cross server bank should be fixed now, let me know if it works and I'll close this ticket. You can see that it's still stored here: http://hiroku.me:27000/oblique/crossserverbank/3adadd7f-c273-4716-95b4-08aa61b2ff35

**Comment by Chewyspedoodle** [comment]
It was transferred, yes. Thank you! Is there a way the mods could see what vouchers I had before the reset?

**Comment by Hiroku** [comment]
I dug through the backed up files and fished out your vouchers, so yes. It's a hard choice though, since I think most people were told their vouchers are dead so if one person gets them returned, there's an expectation that I'll manually dig up all of them which takes me a while. All to say, they may not restore them and I won't hold it against them if that's their choice.

**Comment by Chewyspedoodle** [comment]
Okay. Thanks tons! I'll message a mod and ask if they're willing to give me back just the store bought vouchers all hush hush style. Thanks again! Glad to be back on the server.

**Comment by Hiroku** [comment]
Glad to have you back mate
