### ISSUE TITLE
Ban Appeal, Lord_Tachanks

### ISSUE THREAD

**Issue by Lord-Tachanks** [ObliqueNET/Server#611]
I am appealing my ban on the Oblique server. I understand I exploited a bug that was a part of the Pixelmon Modpack that involved duplication of both the clear and tidal bells. I simply thought as I asked in chat for a tidal bell for decoration that I would add to the clear bells which had their ability to spawn Ho-oh disabled making the items cosmetic and making me simply want them for decoration inside my base. I understand I sold them for money, but if you so choose, you can wipe all the money from my account as I spent no where near close to the amount earned or I can simply pay all the money in my balance to the original shop owner that I sold the bells to (BootyHadMeLike). I will also never exploit any sort of bugs and immediately report them when I discover it.

**Comment by Katadreme** [comment]
Although you have admitted your mistake about duping the bells, and further exploiting this bug by selling these bells, we have yet to see an apology. Which speaks to insincerity of this appeal and how it seems like you're just writing things you'd like us to hear. Admitting to the mistake is good, but not being genuine about it makes it lose all credibility. And because of that, we've decided to deny your request.
