### ISSUE TITLE
drericeto ban appeal

### ISSUE THREAD

**Issue by drericeto** [ObliqueNET/Server#622]
reason: alting
I like playing on this server very much and thats why I played on an alt account. I did not cause any trouble and will not cause any trouble in the future because I learned from my previous ban.

**Comment by drericeto** [comment]
ples unban im so sorry im crying

**Comment by ElementalMP** [comment]
Hm, okay. Well, I believe that you are sorry. Unfortunately, it appears you are sorry for all the wrong reasons. Not an hour after you put in an appeal, (which by the way was at around 4AM for me, I could not possibly have answered within the timeframe you wanted) you attempted to spam ping all the moderators on the server as well as all STAFF on the server, because you wanted us to read your appeal faster, I guess?
 After being told to wait, you decided
![image](https://user-images.githubusercontent.com/31155918/91492424-be9a9280-e909-11ea-98e8-f0469b76ffba.png)
was the best course of action. Normally this is a discord ban. However, staff were lenient, and instead gave you another chance, which you used to ping me personally so I could wake up and read your appeal. 
Ban appeals are for those that believe they have been banned unfairly so they can share their story and gain a second chance should they deserve it.
 Right now, I am looking at discord, **which you are now banned from, FYI** and I see you asking users if they want to see your "huge penis". Given all this, it's rather clear to me that you are indeed sorry. Sorry you got caught, sorry you didn't get your appeal read sooner, and sorry you didn't get unbanned. 
Have a good day 👍

**Comment by drericeto** [comment]
nigger

**Comment by ElementalMP** [comment]
lol, is that the best you can do? You really are 7 years old. Consider yourself banned from this tracker as well.

**Comment by drericeto** [comment]
im serious about the infinite master balls

**Comment by drericeto** [comment]
you should check out the exploit

**Comment by drericeto** [comment]
people on the server already know about the exploit dont need to delete my comment
s
