### ISSUE TITLE
i have 11 iron and 37 coals

### ISSUE THREAD

**Issue by Hellblox** [ObliqueNET/Server#785]

**Comment by Hellblox** [comment]
So I was banned a couple of days ago for mining in the wilderness. I mined with a fortune 2 diamond pick axe and I got 11 iron and 37 coals and some cobblestome and some sand stone, but I was thrown into sand and teleportations out. There then I was banned for no other reason than mineing, I mined with my flavorite diamond pick axe and got banned. please with out cherry on top because I am alergic to cherries unban me please.
![Base Profile Screenshot 2020 08 20 - 00 24 11 14 (2)](https://user-images.githubusercontent.com/72059360/94510554-0fd9c280-01e5-11eb-8c7e-508e53f44ea2.png)

**Comment by Hellblox** [comment]
oops wrong diamond pick asxe

**Comment by Hellblox** [comment]
oops wrong diamond pick asxe

**Comment by Hellblox** [comment]
i have changed tittle 

i unban now pleas
e

**Comment by Hellblox** [comment]
I have not unban and katedream do not reponse me

**Comment by Hiroku** [comment]
![image](https://user-images.githubusercontent.com/1784721/94512003-43a4fe80-025e-11eb-9190-4847334773bb.png)
Missing a valuable detail there mate

**Comment by Hellblox** [comment]
I was digging with my diamond pick axe with fortune 2 in cave i made in wilderness

**Comment by Hellblox** [comment]
but staff did not say that 
i did not see it

**Comment by Hiroku** [comment]
Staff clearly did say that, and the picture shows you replied to them...

**Comment by Katadreme** [comment]
To start off, you weren't banned a few days ago, you we're banned bit more than an hour ago. You were banned because you participated in the Where's Wooper event, in which Hosts and other Staff repeatedly said the rules, and warned you that you were breaking several rules like spam killing, you spam killed me twice as well. After the event ended, you were warned repeatedly that keeping items from the event was not allowed, and you kept several items, then decided to start digging around the build. That was why you were banned. And since you still treat this like a joke, your ban appeal has been declined.

**Comment by Hellblox** [comment]
No i did not
