### ISSUE TITLE
banned from oblique 

### ISSUE THREAD

**Issue by NoahBert** [ObliqueNET/Server#792]
hi, people for oblique I'm really sorry for my behaver on your server I got peer pressured into getting a band. I'm really sorry about that and if you unbanned me ill behave and not be inappropriate

my user name is NoahBert_420 

thanks

**Comment by Katadreme** [comment]
Though you seem to be somewhat genuine, I will be declining your appeal as you went to quite an extent in terms of being not just 'inappropriate' but extremely inappropriate and offensive. We have no tolerance for the kind of things you said shortly before getting banned, and I will not just let you be unbanned because you were simply being 'peer-pressured'.
