### ISSUE TITLE
Banned but didn't get warning

### ISSUE THREAD

**Issue by TKMasterpiece** [ObliqueNET/Server#817]
I was banned for not responding to moderators dm's even though at the time i was afk when i was so i didn't see the messages, also i was not aware of the "dm's feature" as i am new to the game.  I will change the town name as requested aswell.

**Comment by Katadreme** [comment]
I believe you when you say you didn't know about the 'dm feature' since you are very new. However I quite certain you were not afk while staff were asking you to respond to their questions as they have told me you were moving around a lot and you were given ample warnings. And when you were kicked with the kick message displaying 'Can you please respond to staff', you immediately rejoined and continued to ignore staff. Though you didn't know how to use the 'dm feature', you should've attempted to respond in main chat. It is because of this, and also that this was a temporary 3 day ban, that i'll be denying your appeal.
