### ISSUE TITLE
[Support Request] Claiming of an Unclaimed Communal Stand of Apricorns

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#843]
![image](https://user-images.githubusercontent.com/65520757/98489610-ba89cb80-21fc-11eb-85e2-74de9815de4e.png)
A town called Poncho Post claimed a stand of apricorn trees that I am 95% sure were not theirs. The original planter presumably didn't have the funds to claim it all and so claimed none of it. Could you look into this? If the original planter is from Poncho Post, then I apologize for the hassle. Coords are 5296, 71, 6428

**Comment by JustXray** [comment]
Hi freddy, I tped to the coords you listed and it appears this farm has been claimed for 27 weeks by that town, given how long ago that was I'd assume it is indeed their farm. If you still feel this is wrong you can ask a higher staff member to look into it further but I'll provide a screenshot to show you how long it's been claimed.
![image](https://user-images.githubusercontent.com/49011518/104490594-052e1800-559f-11eb-8f66-f1a79aaa393f.png)

**Comment by Rasgnarok** [comment]
Since this has been a few months, I am pre-emptively closing this ticket to keep only active tickets up. If the issue persists, @freddypwner , you can always ping staff in #support on our discord, https://discord.gg/B3XcYcR for quick help. Once again, on behalf of our Moderation team, sorry for the long, long wait!
