### ISSUE TITLE
[Support Request] Neighbor's land didn't autounclaim

### ISSUE THREAD

**Issue by milllks** [ObliqueNET/Server#848]
Username: Milllks
My neighbors claimed land too close to my base and now i can't expand, offline for 128 days and still hasn't converted back into wilderness. Town is called kanto at -546 63 -8198

**Comment by PJLesure** [comment]
Hi milllks! I am going to assume this problem was solved because the coordinates you provided no longer have a town associated with them. However, if you come across this issue again feel free to message Elemental#1635 or Fatyg5#0001 on discord and they will be able to remove the town.

**Comment by Rasgnarok** [comment]
Since this has been a few months, I am pre-emptively closing this ticket to keep only active tickets up. If the issue persists, @milllks , you can always ping staff in #support on our discord, https://discord.gg/B3XcYcR for quick help. Once again, on behalf of our Moderation team, sorry for the long, long wait!
