### ISSUE TITLE
Ban Appeal Because Why Not

### ISSUE THREAD

**Issue by MusheWasTakenScammed** [ObliqueNET/Server#851]
I'm sure there is some format I'm meant to follow for this but alas.

Ign - ThinkTenZ	
Discord - Mushe#6969
Banned On - Both server & Discord.
Age of Ban - About a year and a half.
Reason for Ban - Stated ban reason is "Mushe is banned from Terra gyms"(im not sure i never checked). Nice one Admiral real cool. :)
Real Reason for Ban - Staff disrespect towards Admiral.
Reason for Appeal - Received message from Admiral out of the blue stating and I quote "Tldr getting banned over linoone back then was cringe on my part" So I decided why not appeal.

Alas Thank You

Mushe

**Comment by Rasgnarok** [comment]
_Considering both your and Houndi's appeal is a copy paste, you shall receive a copy-paste reply._

Your ban appeal has been declined, because if you ever understood anything about the reasons for your ban, then you would have taken the time to write a proper appeal... unless you don't care about getting unbanned, since you don't intend to play. Either way, your ban was more than simply a single argument with our Gym Lead, it was a sanction after a cumulative set of events, ranging from disrespect towards Staff, to perm abuse towards players. 

Should you ever want to get unbanned, you can fill out a proper ban appeal, but until then, this mockery of an appeal is declined. By the way, "Ban Appeal Because Why Not" is an excellent way to flag this appeal as "I don't actually care about getting unbanned". Maybe next time the title should be more thoughtful.
