### ISSUE TITLE
Towns not Automatically Getting Town Homes

### ISSUE THREAD

**Issue by Treejan976** [ObliqueNET/Server#857]
Brought this up in the suggestions discord thread and was asked to put it in here. **Multiple new players are having the problem where they create a town, teleport off somewhere / die, and then cant return to their town because they have no town home.** Staff also cannot assist players in returning back to their town if there is no town home since plugin requires a home to be set in order to show coordinates in /t info. This situation tends to lead to the player having to accept losing everything they made in their town and disbanding it (obviously not the best situation, especially for a newer player). 

**According to Hiroku, towns should automatically be placing down a town home when the first chunk is claimed, but this is clearly not happening. Perhaps a bug that should be looked at then?**

**Comment by Hiroku** [comment]
I resolved this, retesting might be good

**Comment by Rasgnarok** [comment]
menno165Today at 5:46 PM
done, doesnt work.
Did created a town that kata will hate since it is called "IAmMenno".
after this I did /t claim and went to spawn after checking if it worked.
From there I did /t home and it did nothing, when trying it will say the following message:
No home to warp to. This is weird.
that is my work report :slight_smile:

**Comment by Rasgnarok** [comment]
Closing, fixed as of this new update.
