### ISSUE TITLE
[Support Request] Cant get to new town

### ISSUE THREAD

**Issue by CharlieMort** [ObliqueNET/Server#870]
i got removed from my old town but my home is still there so when i created a new one i dont have a home there so i cant get back

**Comment by Treejan976** [comment]
Hey, CharlieMort, apologies for the long wait. Could you please tell us the name of your old town? That way we can talk with the town mayor about getting your items retrieved. Thanks!

**Comment by Rasgnarok** [comment]
Since this has been a few months, I am pre-emptively closing this ticket to keep only active tickets up. If the issue persists, @CharlieMort , you can always ping staff in #support on our discord, https://discord.gg/B3XcYcR for quick help. Once again, on behalf of our Moderation team, sorry for the long, long wait!
