### ISSUE TITLE
[CarrotShop] Shop signs not working

### ISSUE THREAD

**Issue by DrPhil405** [ObliqueNET/Server#878]
Everyday I have to re-redstone my shop signs because its almost as if they reset. No one can buy from them, not even me.

**Comment by BootyHadMeLike** [comment]
I have an issue up with a lot of information you might find useful. https://github.com/ObliqueNET/Server/issues/793
To sum it up, If you did not have your shop signs placed like 2 months ago, you have to fix your signs every few days. If you want to change old signs, u basically can't, as it will just revert as well.

**Comment by fatyg5** [comment]
Forgot to mention, this was investigated by me. The issue seems to be rooted in CarrotShop itself, as it should be impossible to set a sign that sells at different prices, yet CarrotShop's JSON is showing one price while the sign shows another. The user was not trying to scam you, just to clear that, but it is a weird issue. We're currently investigating issues with CarrotShop and will post an update when we have a potential fix or replacement. Thank you for the report!

**Comment by Vohras2** [comment]
Closing this for now, as I've not heard any similar reports about it recently. Reopen if the issue happens again.
