### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by meepro27** [ObliqueNET/Server#917]
Hi, I'm RareFraction
I was kicked 2 times and informed not to place an afk farming, and the 2nd one is water afk, and after that some of the admin informed  not to place those again, and so I did follow and leave the game after a mins and after I went back after 2 mins I'm supposed to complete the building I supposed to do but after 2 mins I was banned to the server. I have no Idea what's the reason for the banning since the staff gives me 2 warning and I thought it'll take 3  warnings to get banned.

**Comment by meepro27** [comment]
In addition, I tried to use alternate account to locate the discord of the server, since I'm not joining any discords.

**Comment by Katadreme** [comment]
You'll rarely get 3 chances. Once you get warned for something, and still break server rules afterwards, you wouldn't get given much leeway. However, it says you were very cooperative so due to your good faith, you were given a 2nd chance. You were banned as staff members found you using a AFK machine again after been warned twice that they were against server rules. You were also told to read the server rules on two separate occasions, so clearly we can deduce that you used the afk machine whilst being aware of the rules. And to also add, you got on an alt to ask for the discord when you could've just waited for a response on the ban appeal. You were given many chances, more than most players get, so your ban appeal has been denied.
