### ISSUE TITLE
Ban Appeal For Oblique Discord

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#955]
I got banned from the Oblique Discord a few months ago for taking a meme too seriously and pinging Rasgnarok 17 times.  I regret this. My Discord username is @SoYeah,ImAGamer#3115 and my user ID is 727682189994754158. I feel like I should say something else but I don't know what to say so here's a filler sentence. I won't do it again.

**Comment by Katadreme** [comment]
I don't think needing to tell someone, pinging someone more than say max 3 times is necessary, let alone that someone be the server owner of all people, is a good idea, since most if not all would agree it is common sense. But I guess someone has to take one for the team. A meme is a meme and a joke and is a joke. You've had your time-out off the discord for a while now and am willing to give you a second shot. But let me make this clear. Any such behaviour even remotely close to this is displayed in-game or on discord, you will be banned from both.
