### ISSUE TITLE
ObliqueMC.com website issues.

### ISSUE THREAD

**Issue by MJDeveloping** [ObliqueNET/Server#963]
This is a post that I'll be updating as I find issues, but since there are two issues I know of that hasn't been fixed despite being there for well over a year now, I think it's about time that I made an actual report about it.

- Social icon for "Github" leads to a dead link ("https://github.com/ObliqueNetwork") (The Server -> Support link is correct, however)
- Social icon for Steam group leads to an active link, but the staff of that group obviously hasn't been maintained in a long time...
- The Terra Applications page needs some updating... Admiral is still listed as "Gym Lead", Elemental as "lead mod", Ekul as wizard lead... you get the picture.

Not rushing for any of these to be fixed, but as far as I could find, there wasn't any mention of it elsewhere, so here is a place that won't vanish :D

**Comment by Rasgnarok** [comment]
- Updated our Staff page to reflect Lead changes, namely DoughnutChicken, Katadreme, Ooomaloo, https://www.obliquemc.com/staff.
- Updated our homepage to reflect our single-running server, https://www.obliquemc.com/.
- Updated our Map on site so that Mia doesn't look incompetent, https://www.obliquemc.com/map.
- Updated our Team page to reflect @Elemental 's addition to Manager, https://www.obliquemc.com/team.
- Updated our Wiki https://www.obliquemc.com/wiki page, now comfortably directing back to https://github.com/ObliqueNET/Server/wiki.
- Updated our Support https://www.obliquemc.com/support page, now comfortably redirecting to https://github.com/ObliqueNET/Server/issues.
- Cleaned up some awkward transitions in our submenu, and some belated mentions of Terra and Stratos.
- Corrected a typo in our Enigma overlay description - you get 3 shiny ups, not 2 https://www.obliquemc.com/store.
- Fixed our Steam Community button and it's availability. It is now a public group. Join here: https://steamcommunity.com/groups/obliquenetwork . It still needs some setup, and I'll be adding staff members as we move along. Old Steam group was sadly deprecated, and it was a staff initiative from a person now retired.
- Updated our FREE STARTER POKÉDISGUISE pack to include Generation 7 and 8 starter Pokémon evolutionary lines.
