### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Kirikoz** [ObliqueNET/Server#964]
Hello to whom it concerns,

I woke up today to get messages from friends to find out that I was banned today for my words yesterday in staff chat, which I truly apologize for. It was in a fit of irritation, and doesn't really show my true self. Nonetheless, I do have some points I'd like to bring up that concern my ban.  First of all, my claims were meant to not be serious and instead sarcastic. In my eyes, they looked like a mere joke; one that was said over multiple times by many players in the past. 
For instance: 
![xray](https://user-images.githubusercontent.com/65331193/105408301-a2163400-5be3-11eb-8fa2-9c1d9a3636ca.PNG)
In this scenario a staff member said this yet they weren’t banned or reprimanded for their comments, since we all took them as jokes.  I tried to include "lmao and emoticon faces'' after every comment to lighten the mood and indicate them as jokes, but I have to admit that it wasn't the best of "jokes" especially during times like these. This leads me to pose the question, is what I said truly bannable if we are being reasonably consistent?

Even if they weren't interpreted as jokes, the thing I said was stated by former staff who has talked against the server and my town too. They currently still are staff, and have not been temped or permabanned. 
![cen1](https://user-images.githubusercontent.com/65331193/105408351-b3f7d700-5be3-11eb-9c53-16cf96d10a84.PNG)
![cen2](https://user-images.githubusercontent.com/65331193/105408366-b6f2c780-5be3-11eb-92b9-3dad13120675.PNG)
Unlike me, however, they truly have shown they weren't just joking as they did sell breedables for relatively low prices at the time. And yet once again, there was no consequence as severe as a ban. My ban message includes "conspiring to ruin the eco'', yet we can tell from throughout all of the reset, Prof, my town, and I are very adamant against the sale of breedables and the maintenance of keeping balance in the breeding economy. We haven't even sold a breedable, given our money, or legends at all. even when we said we were leaving, and many people could testify to that. It was just a misunderstood joke, that I don't necessarily blame you, yet concern the rash approach to instantly ban me.

My ban msg additionally included "conspiring", which although is untrue is also, according to previous altercations, not a reasonable reason to ban someone. We have shown no method of "breaking the eco", and looking at the Mount Mithras incident, I do not want to bring it up in public, and I'm sure you understand the seriousness of the allegation. The players that were caught suffered no consequence besides a warning. As they, shown in the image, were just "planning" not necessarily "doing anything yet". I question why I can't receive this response as well (even though once again, my comments were a joke). Their behavior would have also disrupted the economy and put them in an unfair advantage.  
![mithras1](https://user-images.githubusercontent.com/65331193/105408841-59ab4600-5be4-11eb-9d3b-2e78a3aec04d.PNG)
![mithras2](https://user-images.githubusercontent.com/65331193/105408854-5f089080-5be4-11eb-845f-45783c5c0e2c.PNG)

I would like to use this time to explain I am not using these evidence to bring the current staffers down, nor do I wish they fail or such. It just seems quite inconsistent to ban me for this when it was shown in precedent that it does not justify a ban. If undercutting is a problem, it's something that plenty do and it's currently happening, something I was against which inspired my sarcastic joke. Once again, I apologize if I had made any staff uncomfortable with my comments, and I understand that a threat against "the whole server eco" is serious. So, I don't necessarily blame the decision, just blame the consistency and rashness of the ban. It made me question whether or not my town was on some predetermined hitlist waiting for us to "slip".  It was all a misunderstood joke, but I do wish to hear your response soon and thank you.

**Comment by Rasgnarok** [comment]
Ban reason: Disrespecting staff, disrespecting players with malicious economy crashing intent. Ban appeal on Github.
![image](https://user-images.githubusercontent.com/18584380/105655125-76b67200-5e8d-11eb-9d5c-7daa93a7ec7f.png)
![image](https://user-images.githubusercontent.com/18584380/105655134-7b7b2600-5e8d-11eb-9e97-43127f931224.png)

Past offenses from other staff, from nearly a year ago, are not enough hide your intent that you clearly spelled in staff chat. 

You prefer to forget the comments you made on the night of your ban, so be it. They are still the reason for your ban, not any of your past comments. It does not absolve any other community member from any 'crime', but it is also entirely irrelevant to your responsibility towards your own words.

Your ban appeal is declined, as ban appeals are meant to confront your own actions, not that of others. I would suggest never announcing in staff chat your intentions to 'undercut everyone',. I would neither recommend stating you are now 'here to be a dickwad' and that you're not 'here to solve problems'. We can see you.

Staff solve problems, and ex-staff, like you, should know better. Your firing was escalated to a ban under those premises, and it will remain until you face your own actions instead of hiding behind that of others.
