### ISSUE TITLE
Quest: Supply Lines (Incorrect Values)

### ISSUE THREAD

**Issue by purifiedrabbits** [ObliqueNET/Server#965]
Step two of this quest: 
-Collect:  -10 Raw Beef
               -10 Raw Chicken
               -5 Wool

-Registers at:  -5 Raw Beef
               -5 Raw Chicken
               -5 Wool

**Comment by menno516** [comment]
I have checked this and it marks it done when each 10 beef, 10 chicken and 5 wool have been gathered. (stage 1) (stage 2 is return to the NPC with the items)

The only thing that I noticed is that it says "some" instead of the right amount.

![image_2021-01-24_132637](https://user-images.githubusercontent.com/63118334/105630170-c8d4a480-5e47-11eb-8a84-e68ac98eac7f.png)

**Comment by purifiedrabbits** [comment]
Weird, because the user Septimuz had this issue in #support and told me that it checked off at 5 but didn't have enough for the next part. It is possible he dropped it and picked it back up again, thus doubling what he got, unsure though.

**Comment by PrimalCyndaquil** [comment]
I've checked the file for this quest and the 10, 10, 5 comment by menno checks out. Most likely an issue with player dropping and picking up the item as purifiedrabbits said.
