### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Daegonna** [ObliqueNET/Server#978]
Oke so about 30 min ago i was banned. Reason not sure! Staff was talking to me i tried responding but i'm not a fast typer cuz i can't type fast and i didn't directly knew the comment to respond, when they told me i was in the middle of my response when i got banned. They where asking about afk avoidence. The response i was typing was : i wasn't afk i was sorting my pokemon in my pc en getting stuff to evolve some of my mons. When i am in my chestchamber i'm always on my Togekiss so i am able to reach the topchest more easily.  So i was trying to coopperate but didn't directly knew how 2 respond. i did respond using the normal chat tho and that seemed 2 piss him/her off.

**Comment by Katadreme** [comment]
Staff claim they tried very hard to get your attention by trying to talking to you and tping to you, of which you were unresponsive to. I understand you were looking your chest / pc, but you were looking at this chest/pc for more than 10minutes. Since this was only a temporary ban, which is going to be lifted in about another 24hrs, think its best you just wait it out.

**Comment by Daegonna** [comment]
Why am i blocked again??? No1 talked 2 me. I haven't been online for 2 days. Before that i was mainly working on our town coz i'm literly 2 afraid 2 leave 2 the wild. Now i aperently did something wrong again whitout even knowing. For as far as i know i haven't even been close 2 other ppls bases
