### ISSUE TITLE
Legendary Pokemon in "Cataclysmic Nature" doesn´t spawn

### ISSUE THREAD

**Issue by TheScorpion698** [ObliqueNET/Server#997]
The legendary Pokemon in this Quest encountered me but then the Server restarted. After that the Pokemon didn´t showed up again.

**Comment by PrimalCyndaquil** [comment]
I've checked the file for this quest and the battles with Zeraora featured in it. Each of these battle stages has the correct objectives for a case like this. This means that this issue is most likely related to #956 , as the Zeraora battle triggers happened while the player was offline. Closing this, please let a QD know if you still need them to fix your quest manually.
